import './less/style.less';
import menuScript from './js/menu';
import sliderScript from './js/slider';
import modalScript from './js/modal';
import anchorsScript from './js/anchors';
import scrollToTopScript from './js/scrollToTop';
import stickyMenuScript from './js/stickyMenu';
import fileUpload from './js/fileUpload';
import modalFormRequest from './js/modalFormRequest';
import photoFormRequest from './js/photoFormRequest';
import dismantlingSlider from './js/dismantlingSlider';
/* eslint-disable */
import like from '../img/like.svg';
import weight from '../img/weight.svg';
import truck from '../img/truck.svg';
import man from '../img/man.svg';
import money from '../img/money.svg';
import phone from '../img/phone.svg';
import photo from '../img/photo.svg';
import lock from '../img/lock.svg';
import goodMoney from '../img/goodMoney.svg';
import creditCard from '../img/creditCard.svg';
import iconMenuBurger from '../img/iconMenuBurger.svg';
import iconMenuCross from '../img/iconMenuCross.svg';
import clock from '../img/clock.svg';
import cursor from '../img/cursor.svg';
import success from '../img/success.svg';
import error from '../img/error.svg';
/* eslint-enable */

menuScript();
sliderScript();
modalScript();
anchorsScript();
scrollToTopScript();
stickyMenuScript();
fileUpload();
modalFormRequest();
photoFormRequest();
dismantlingSlider();
